// Crucible Design Tokens - Generated by Crucible
// NativeWind Tailwind preset. Add to tailwind.config.js: `presets: [require('./tailwind.preset.js')]`.
module.exports = {
  theme: {
    extend: {
      colors: {
  "primary": {
    "DEFAULT": "#6C63FF",
    "foreground": "#FFFFFF"
  },
  "secondary": {
    "DEFAULT": "#F3F2FF",
    "foreground": "#1A1A2E"
  },
  "surface": "#FFFFFF",
  "background": "#F8F9FA",
  "border": "#E2E1F0",
  "text": "#1A1A2E",
  "textMuted": "#6B6B8A",
  "destructive": {
    "DEFAULT": "#E24B4A",
    "foreground": "#FFFFFF"
  },
  "success": "#1D9E75",
  "accent": {
    "foreground": "#1A1A2E"
  },
  "foreground": "#1A1A2E"
},
      borderRadius: {
  "sm": "4px",
  "md": "8px",
  "lg": "12px"
},
    },
  },
};
