// Crucible Design Tokens - Generated by Crucible
// StyleSheet theme object for React Native (use with StyleSheet.create).
export const theme = {
  "colorPrimary": "#6C63FF",
  "colorSecondary": "#F3F2FF",
  "colorSurface": "#FFFFFF",
  "colorBackground": "#F8F9FA",
  "colorBorder": "#E2E1F0",
  "colorText": "#1A1A2E",
  "colorTextMuted": "#6B6B8A",
  "colorDestructive": "#E24B4A",
  "colorSuccess": "#1D9E75",
  "colorPrimaryForeground": "#FFFFFF",
  "colorSecondaryForeground": "#1A1A2E",
  "colorDestructiveForeground": "#FFFFFF",
  "colorAccentForeground": "#1A1A2E",
  "foreground": "#1A1A2E",
  "radiusSm": "4px",
  "radiusMd": "8px",
  "radiusLg": "12px",
  "spacingUnit": "4px"
} as const;
