export const COMPONENT_TOKEN_DEFAULTS: Record<string, Record<string, string>> = {
  card: {
    headerPadding: 'calc(var(--spacing-unit) * 6)',
    contentPadding: 'calc(var(--spacing-unit) * 6)',
    footerPadding: 'calc(var(--spacing-unit) * 6)',
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--color-surface)',
    borderColor: 'var(--color-border)',
    shadow: '0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)',
  },
  button: {
    heightSm: 'calc(var(--spacing-unit) * 9)',
    heightMd: 'calc(var(--spacing-unit) * 10)',
    heightLg: 'calc(var(--spacing-unit) * 11)',
    paddingXSm: 'calc(var(--spacing-unit) * 3)',
    paddingXMd: 'calc(var(--spacing-unit) * 4)',
    paddingXLg: 'calc(var(--spacing-unit) * 8)',
    borderRadius: 'var(--radius-md)',
    fontWeight: '500',
    transition: 'background-color 0.2s ease, color 0.2s ease, box-shadow 0.2s ease',
  },
  input: {
    height: 'calc(var(--spacing-unit) * 10)',
    paddingX: 'calc(var(--spacing-unit) * 3)',
    borderRadius: 'var(--radius-md)',
    borderColor: 'var(--color-border)',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  form: {
    groupGap: 'calc(var(--spacing-unit) * 5)',
    itemGap: 'calc(var(--spacing-unit) * 1.5)',
    labelColor: 'var(--color-text)',
    labelWeight: '500',
    requiredColor: 'var(--color-destructive)',
    controlHeightSm: 'calc(var(--spacing-unit) * 9)',
    controlHeightMd: 'calc(var(--spacing-unit) * 10)',
    controlHeightLg: 'calc(var(--spacing-unit) * 11)',
    errorColor: 'var(--color-destructive)',
    descriptionColor: 'var(--color-text-muted)',
    descriptionSize: '0.75rem',
    radius: 'var(--radius-md)',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
  },
  Dialog: {
    padding: 'calc(var(--spacing-unit) * 6)',
    borderRadius: 'var(--radius-lg)',
    overlayBg: 'rgba(0, 0, 0, 0.4)',
    shadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)',
    zIndex: '1000',
  },
  select: {
    height: 'calc(var(--spacing-unit) * 10)',
    paddingX: 'calc(var(--spacing-unit) * 3)',
    borderRadius: 'var(--radius-md)',
    optionPadding: 'calc(var(--spacing-unit) * 2.5)',
    dropdownShadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    zIndex: '900',
  },
  table: {
    rowHeight: 'calc(var(--spacing-unit) * 10)',
    headerHeight: 'calc(var(--spacing-unit) * 10)',
    borderRadius: 'var(--radius-md)',
    paginationHeight: 'calc(var(--spacing-unit) * 8)',
    virtualOverscan: '5',
    cellPadding: 'calc(var(--spacing-unit) * 3)',
    rowHoverBg: 'var(--color-secondary)',
    stripedBg: 'var(--color-background)',
  },
  popover: {
    background: 'var(--color-surface)',
    border: 'var(--color-border)',
    shadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    radius: 'var(--radius-md)',
    padding: 'calc(var(--spacing-unit) * 2)',
    zIndex: '50',
  },
  tooltip: {
    background: 'var(--color-surface)',
    border: 'var(--color-border)',
    text: 'var(--color-text)',
    shadow: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)',
    radius: 'var(--radius-md)',
    padding: 'calc(var(--spacing-unit) * 2)',
    zIndex: '60',
  },
  toast: {
    background: 'var(--color-surface)',
    border: 'var(--color-border)',
    text: 'var(--color-text)',
    textMuted: 'var(--color-text-muted)',
    radius: 'var(--radius-md)',
    shadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    padding: 'calc(var(--spacing-unit) * 4)',
    gap: 'calc(var(--spacing-unit) * 2)',
    zIndex: '9999',
    successBg: 'var(--color-success)',
    errorBg: 'var(--color-destructive)',
    warningBg: '#f59e0b',
    infoBg: 'var(--color-primary)',
  },
  label: {
    color: 'var(--color-text)',
    weight: '500',
    requiredColor: 'var(--color-destructive)',
    gap: 'calc(var(--spacing-unit) * 1)',
    disabledOpacity: '0.6',
  },
  separator: {
    color: 'var(--color-border)',
    thickness: '1px',
    spacing: 'calc(var(--spacing-unit) * 2)',
    labelColor: 'var(--color-text-muted)',
    labelGap: 'calc(var(--spacing-unit) * 2)',
  },
  badge: {
    radius: 'var(--radius-sm)',
    fontSize: '0.75rem',
    fontWeight: '500',
    gap: 'calc(var(--spacing-unit) * 1)',
    primaryBg: 'var(--color-primary)',
    secondaryBg: 'var(--color-secondary)',
    successBg: 'var(--color-success)',
    warningBg: '#f59e0b',
    destructiveBg: 'var(--color-destructive)',
    onColor: '#ffffff',
  },
  tabs: {
    listGap: 'calc(var(--spacing-unit) * 1)',
    triggerHeightSm: 'calc(var(--spacing-unit) * 8)',
    triggerHeightMd: 'calc(var(--spacing-unit) * 9)',
    triggerHeightLg: 'calc(var(--spacing-unit) * 11)',
    triggerPaddingX: 'calc(var(--spacing-unit) * 3)',
    triggerRadius: 'var(--radius-md)',
    triggerColor: 'var(--color-text-muted)',
    triggerActiveColor: 'var(--color-text)',
    triggerHoverBg: 'var(--color-secondary)',
    triggerActiveBg: 'var(--color-surface)',
    triggerActiveIndicator: 'var(--color-primary)',
    indicatorThickness: '2px',
    contentPaddingY: 'calc(var(--spacing-unit) * 4)',
    transition: 'background-color 0.2s ease, color 0.2s ease, box-shadow 0.2s ease',
  },
};
